import * as cdk from 'aws-cdk-lib';
import * as cognito from 'aws-cdk-lib/aws-cognito';
import * as apigatewayv2 from 'aws-cdk-lib/aws-apigatewayv2';
import * as apigatewayv2Integrations from 'aws-cdk-lib/aws-apigatewayv2-integrations';
import * as apigatewayv2Authorizers from 'aws-cdk-lib/aws-apigatewayv2-authorizers';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as sns from 'aws-cdk-lib/aws-sns';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as cloudfront from 'aws-cdk-lib/aws-cloudfront';
import * as origins from 'aws-cdk-lib/aws-cloudfront-origins';
import * as acm from 'aws-cdk-lib/aws-certificatemanager';
import * as route53 from 'aws-cdk-lib/aws-route53';
import * as route53Targets from 'aws-cdk-lib/aws-route53-targets';
import * as cr from 'aws-cdk-lib/custom-resources';
import * as logs from 'aws-cdk-lib/aws-logs';
import { Construct } from 'constructs';
import * as path from 'path';
import * as lambdaPython from '@aws-cdk/aws-lambda-python-alpha';

export interface ElevatorStackProps extends cdk.StackProps {
  envName: string;
  elevatorAdminGroup: string;
  elevatorAuditorGroup: string;
  idcRegion?: string;
  customDomain?: string;
  idcAccessGroup: string;
  allowLocalhost?: boolean;
}

export class ElevatorStack extends cdk.Stack {
  public readonly userPool: cognito.UserPool;
  public readonly userPoolClient: cognito.UserPoolClient;
  public readonly api: apigatewayv2.HttpApi;

  constructor(scope: Construct, id: string, props: ElevatorStackProps) {
    super(scope, id, props);

    const { envName } = props;

    // =============================================================================
    // SNS Topic for Notifications
    // =============================================================================
    const notificationTopic = new sns.Topic(this, 'NotificationTopic', {
      displayName: 'Elevator Notification Topic',
      topicName: `elevator-notifications-${envName}`,
    });

    new cdk.CfnOutput(this, 'NotificationTopicArn', {
      value: notificationTopic.topicArn,
    });

    // =============================================================================
    // S3 Bucket for CloudTrail Lake Query Results
    // =============================================================================
    new s3.Bucket(this, 'ElevatorBucket', {
      bucketName: `elevator-cloudtrail-bucket-${envName}-${this.account}`,
      encryption: s3.BucketEncryption.S3_MANAGED,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      enforceSSL: true,
      versioned: true,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });

    // =============================================================================
    // CloudTrail Lake Event Data Store
    // =============================================================================
    const eventDataStore = new cdk.aws_cloudtrail.CfnEventDataStore(this, 'EventDataStore', {
      // name is auto-generated by CloudFormation to avoid conflicts with pending deletions
      retentionPeriod: 90,
      multiRegionEnabled: true,
      organizationEnabled: true,
      ingestionEnabled: true,
      terminationProtectionEnabled: false,
      advancedEventSelectors: [
        {
          fieldSelectors: [
            {
              field: 'eventCategory',
              equalTo: ['Management'],
            },
            {
              // Filter for write-only events (non-read-only)
              field: 'readOnly',
              equalTo: ['false'],
            },
          ],
        },
      ],
    });

    new cdk.CfnOutput(this, 'EventDataStoreOutput', {
      value: eventDataStore.attrEventDataStoreArn,
    });

    // =============================================================================
    // DynamoDB Tables
    // =============================================================================
    const requestsTable = new dynamodb.Table(this, 'RequestsTable', {
      tableName: `elevator-requests-${envName}`,
      partitionKey: { name: 'id', type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      pointInTimeRecoverySpecification: {
        pointInTimeRecoveryEnabled: true,
      },
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });

    requestsTable.addGlobalSecondaryIndex({
      indexName: 'byEmailAndStatus',
      partitionKey: { name: 'email', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'status', type: dynamodb.AttributeType.STRING },
    });

    requestsTable.addGlobalSecondaryIndex({
      indexName: 'byApproverAndStatus',
      partitionKey: { name: 'approverId', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'status', type: dynamodb.AttributeType.STRING },
    });

    const approversTable = new dynamodb.Table(this, 'ApproversTable', {
      tableName: `elevator-approvers-${envName}`,
      partitionKey: { name: 'id', type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      pointInTimeRecoverySpecification: {
        pointInTimeRecoveryEnabled: true,
      },
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });

    const settingsTable = new dynamodb.Table(this, 'SettingsTable', {
      tableName: `elevator-settings-${envName}`,
      partitionKey: { name: 'id', type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      pointInTimeRecoverySpecification: {
        pointInTimeRecoveryEnabled: true,
      },
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });

    const eligibilityTable = new dynamodb.Table(this, 'EligibilityTable', {
      tableName: `elevator-eligibility-${envName}`,
      partitionKey: { name: 'id', type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      pointInTimeRecoverySpecification: {
        pointInTimeRecoveryEnabled: true,
      },
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });

    const integrationsTable = new dynamodb.Table(this, 'IntegrationsTable', {
      tableName: `elevator-integrations-${envName}`,
      partitionKey: { name: 'name', type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      pointInTimeRecoverySpecification: {
        pointInTimeRecoveryEnabled: true,
      },
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });

    // =============================================================================
    // S3 Bucket + CloudFront for Frontend
    // =============================================================================
    const websiteBucket = new s3.Bucket(this, 'WebsiteBucket', {
      bucketName: `elevator-website-${envName}-${this.account}`,
      encryption: s3.BucketEncryption.S3_MANAGED,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      enforceSSL: true,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
      autoDeleteObjects: false,
    });

    const originAccessIdentity = new cloudfront.OriginAccessIdentity(this, 'OAI', {
      comment: `OAI for Elevator website - ${envName}`,
    });

    websiteBucket.grantRead(originAccessIdentity);

    // Look up ACM certificate and Route53 hosted zone dynamically via custom resources
    let certificate: acm.ICertificate | undefined;
    let hostedZone: route53.IHostedZone | undefined;

    if (props.customDomain) {
      // Look up certificate ARN dynamically (must be in us-east-1 for CloudFront)
      const findCertFunction = new lambda.Function(this, 'FindCertFunction', {
        code: lambda.Code.fromInline(`
import boto3
import cfnresponse

def handler(event, context):
    try:
        if event['RequestType'] == 'Delete':
            cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
            return

        domain = event['ResourceProperties']['DomainName']
        acm = boto3.client('acm', region_name='us-east-1')

        paginator = acm.get_paginator('list_certificates')
        for page in paginator.paginate(CertificateStatuses=['ISSUED']):
            for cert in page['CertificateSummaryList']:
                if cert['DomainName'] == domain:
                    cfnresponse.send(event, context, cfnresponse.SUCCESS, {
                        'CertificateArn': cert['CertificateArn']
                    })
                    return

        cfnresponse.send(event, context, cfnresponse.FAILED, {}, reason=f'No issued certificate found for {domain}')
    except Exception as e:
        cfnresponse.send(event, context, cfnresponse.FAILED, {}, reason=str(e))
`),
        runtime: lambda.Runtime.PYTHON_3_12,
        handler: 'index.handler',
        timeout: cdk.Duration.seconds(30),
        logRetention: logs.RetentionDays.ONE_WEEK,
      });

      findCertFunction.addToRolePolicy(new iam.PolicyStatement({
        actions: ['acm:ListCertificates'],
        resources: ['*'],
      }));

      const certResource = new cdk.CustomResource(this, 'CertificateResource', {
        serviceToken: findCertFunction.functionArn,
        properties: {
          DomainName: props.customDomain,
        },
      });

      const certificateArn = certResource.getAttString('CertificateArn');
      certificate = acm.Certificate.fromCertificateArn(this, 'ImportedCertificate', certificateArn);

      // Look up Route53 hosted zone dynamically
      const findZoneFunction = new lambda.Function(this, 'FindZoneFunction', {
        code: lambda.Code.fromInline(`
import boto3
import cfnresponse

def handler(event, context):
    try:
        if event['RequestType'] == 'Delete':
            cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
            return

        domain = event['ResourceProperties']['DomainName']
        route53 = boto3.client('route53')

        paginator = route53.get_paginator('list_hosted_zones')
        for page in paginator.paginate():
            for zone in page['HostedZones']:
                # Zone name has trailing dot
                if zone['Name'] == domain + '.':
                    zone_id = zone['Id'].replace('/hostedzone/', '')
                    cfnresponse.send(event, context, cfnresponse.SUCCESS, {
                        'HostedZoneId': zone_id
                    })
                    return

        cfnresponse.send(event, context, cfnresponse.FAILED, {}, reason=f'No hosted zone found for {domain}')
    except Exception as e:
        cfnresponse.send(event, context, cfnresponse.FAILED, {}, reason=str(e))
`),
        runtime: lambda.Runtime.PYTHON_3_12,
        handler: 'index.handler',
        timeout: cdk.Duration.seconds(30),
        logRetention: logs.RetentionDays.ONE_WEEK,
      });

      findZoneFunction.addToRolePolicy(new iam.PolicyStatement({
        actions: ['route53:ListHostedZones'],
        resources: ['*'],
      }));

      const zoneResource = new cdk.CustomResource(this, 'HostedZoneResource', {
        serviceToken: findZoneFunction.functionArn,
        properties: {
          DomainName: props.customDomain,
        },
      });

      const hostedZoneId = zoneResource.getAttString('HostedZoneId');
      hostedZone = route53.HostedZone.fromHostedZoneAttributes(this, 'ImportedHostedZone', {
        hostedZoneId,
        zoneName: props.customDomain,
      });
    }

    const distribution = new cloudfront.Distribution(this, 'Distribution', {
      comment: `Elevator Distribution - ${envName}`,
      defaultBehavior: {
        origin: new origins.S3Origin(websiteBucket, {
          originAccessIdentity,
        }),
        viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
      },
      defaultRootObject: 'index.html',
      errorResponses: [
        {
          httpStatus: 404,
          responseHttpStatus: 200,
          responsePagePath: '/index.html',
        },
        {
          httpStatus: 403,
          responseHttpStatus: 200,
          responsePagePath: '/index.html',
        },
      ],
      // Custom domain configuration
      ...(props.customDomain && certificate
        ? {
            domainNames: [props.customDomain],
            certificate,
          }
        : {}),
    });

    // Create A record for custom domain pointing to CloudFront
    if (props.customDomain && hostedZone) {
      new route53.ARecord(this, 'CustomDomainARecord', {
        zone: hostedZone,
        recordName: props.customDomain,
        target: route53.RecordTarget.fromAlias(new route53Targets.CloudFrontTarget(distribution)),
      });
    }

    const siteUrl = `https://${distribution.distributionDomainName}/`;
    const externalUrl = props.customDomain ? `https://${props.customDomain}/` : undefined;
    // Primary login URL: external domain if set, otherwise CloudFront
    const primaryLoginUrl = externalUrl || siteUrl;

    // =============================================================================
    // Cognito User Pool
    // =============================================================================
    this.userPool = new cognito.UserPool(this, 'UserPool', {
      userPoolName: `elevator-user-pool-${envName}`,
      selfSignUpEnabled: false,
      signInAliases: {
        email: true,
      },
      autoVerify: {
        email: true,
      },
      standardAttributes: {
        email: {
          required: true,
          mutable: true,
        },
      },
      passwordPolicy: {
        minLength: 8,
        requireLowercase: true,
        requireUppercase: true,
        requireDigits: true,
        requireSymbols: true,
      },
      accountRecovery: cognito.AccountRecovery.EMAIL_ONLY,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });

    // Create Cognito groups
    new cognito.CfnUserPoolGroup(this, 'AdminGroup', {
      userPoolId: this.userPool.userPoolId,
      groupName: 'Admin',
      description: 'Admin users with full access',
      precedence: 1,
    });

    new cognito.CfnUserPoolGroup(this, 'AuditorsGroup', {
      userPoolId: this.userPool.userPoolId,
      groupName: 'Auditors',
      description: 'Auditor users with read-only access',
      precedence: 2,
    });

    // Add Cognito domain for OAuth
    const userPoolDomain = this.userPool.addDomain('UserPoolDomain', {
      cognitoDomain: {
        domainPrefix: `elevator-${envName}-${this.account}`,
      },
    });

    // Build callback URLs list
    const callbackUrls = [siteUrl];
    if (props.allowLocalhost) {
      callbackUrls.push('http://localhost:5173/');
    }
    if (externalUrl) {
      callbackUrls.push(externalUrl);
    }

    // =============================================================================
    // IAM Identity Center SAML Application (Custom Resource)
    // =============================================================================
    const idcRegion = props.idcRegion || this.region;
    const idcAccessGroup = props.idcAccessGroup;
    const oauthDomainPrefix = `elevator-${envName}-${this.account}`;

    // Lambda for managing IDC SAML application (no external dependencies, uses built-in boto3)
    const idcAppFunction = new lambda.Function(this, 'IdcAppFunction', {
      code: lambda.Code.fromAsset(path.join(__dirname, '../../lambda/idc-app')),
      runtime: lambda.Runtime.PYTHON_3_12,
      handler: 'index.handler',
      timeout: cdk.Duration.minutes(5),
      logRetention: logs.RetentionDays.ONE_WEEK,
    });

    // Grant permissions for IDC operations
    idcAppFunction.addToRolePolicy(new iam.PolicyStatement({
      actions: [
        'sso:*',
        'identitystore:ListGroups',
      ],
      resources: ['*'],
    }));

    // Custom Resource Provider
    const idcAppProvider = new cr.Provider(this, 'IdcAppProvider', {
      onEventHandler: idcAppFunction,
      logRetention: logs.RetentionDays.ONE_WEEK,
    });

    // Custom Resource for IDC SAML Application
    const idcApp = new cdk.CustomResource(this, 'IdcApp', {
      serviceToken: idcAppProvider.serviceToken,
      properties: {
        idcRegion: idcRegion,
        cognitoRegion: this.region,
        userPoolId: this.userPool.userPoolId,
        oauthDomain: oauthDomainPrefix,
        accessGroup: idcAccessGroup,
        appName: 'Elevator',
        appDescription: 'Temporary Elevated Access Management',
      },
    });

    // Get metadata URL from Custom Resource
    const samlMetadataUrl = idcApp.getAttString('metadataUrl');

    // Create SAML Identity Provider
    const supportedIdentityProviders: cognito.UserPoolClientIdentityProvider[] = [
      cognito.UserPoolClientIdentityProvider.COGNITO,
    ];

    const samlProvider = new cognito.UserPoolIdentityProviderSaml(this, 'IDCSamlProvider', {
      userPool: this.userPool,
      name: 'IDC',
      metadata: cognito.UserPoolIdentityProviderSamlMetadata.url(samlMetadataUrl),
      attributeMapping: {
        email: cognito.ProviderAttribute.other('Email'),
      },
    });
    supportedIdentityProviders.push(cognito.UserPoolClientIdentityProvider.custom(samlProvider.providerName));

    this.userPoolClient = new cognito.UserPoolClient(this, 'UserPoolClient', {
      userPool: this.userPool,
      authFlows: {
        userPassword: true,
        userSrp: true,
      },
      supportedIdentityProviders,
      oAuth: {
        flows: {
          authorizationCodeGrant: true,
          implicitCodeGrant: true,
        },
        scopes: [cognito.OAuthScope.EMAIL, cognito.OAuthScope.OPENID, cognito.OAuthScope.PROFILE],
        callbackUrls,
        logoutUrls: callbackUrls,
      },
    });


    // =============================================================================
    // API Gateway v2 HTTP API
    // =============================================================================

    // Create Cognito JWT Authorizer
    const authorizer = new apigatewayv2Authorizers.HttpUserPoolAuthorizer('CognitoAuthorizer', this.userPool, {
      userPoolClients: [this.userPoolClient],
      identitySource: ['$request.header.Authorization'],
    });

    // Create HTTP API
    this.api = new apigatewayv2.HttpApi(this, 'Api', {
      apiName: `elevator-api-${envName}`,
      description: 'Elevator HTTP API',
      corsPreflight: {
        allowOrigins: ['*'],
        allowMethods: [apigatewayv2.CorsHttpMethod.ANY],
        allowHeaders: ['*'],
        maxAge: cdk.Duration.days(1),
      },
    });

    // =============================================================================
    // Lambda Functions
    // =============================================================================

    // =============================================================================
    // Unified Backend Lambda Function
    // =============================================================================

    // Helper function to grant common permissions
    const grantCommonPermissions = (func: lambda.Function) => {
      // Grant DynamoDB permissions
      requestsTable.grantReadWriteData(func);
      approversTable.grantReadWriteData(func);
      settingsTable.grantReadWriteData(func);
      eligibilityTable.grantReadWriteData(func);
      integrationsTable.grantReadWriteData(func);

      // Grant SNS permissions
      notificationTopic.grantPublish(func);

      // Grant SES permissions
      func.addToRolePolicy(
        new iam.PolicyStatement({
          actions: ['ses:SendEmail'],
          resources: ['*'],
        })
      );

      // Grant SSO Admin permissions
      func.addToRolePolicy(
        new iam.PolicyStatement({
          actions: [
            'sso:CreateAccountAssignment',
            'sso:DeleteAccountAssignment',
            'sso:DescribeAccountAssignmentCreationStatus',
            'sso:DescribeAccountAssignmentDeletionStatus',
            'sso:ListPermissionSets',
            'sso:ListPermissionSetsProvisionedToAccount',
            'sso:DescribePermissionSet',
            'sso:ListInstances',
          ],
          resources: ['*'],
        })
      );

      // Grant Identity Store permissions
      func.addToRolePolicy(
        new iam.PolicyStatement({
          actions: [
            'identitystore:ListUsers',
            'identitystore:ListGroups',
            'identitystore:ListGroupMemberships',
            'identitystore:ListGroupMembershipsForMember',
            'identitystore:GetUserId',
            'identitystore:GetGroupId',
            'identitystore:DescribeUser',
          ],
          resources: ['*'],
        })
      );

      // Grant Organizations permissions
      func.addToRolePolicy(
        new iam.PolicyStatement({
          actions: [
            'organizations:ListAccounts',
            'organizations:DescribeOrganization',
            'organizations:ListOrganizationalUnitsForParent',
            'organizations:ListRoots',
            'organizations:ListAccountsForParent',
            'organizations:ListParents',
          ],
          resources: ['*'],
        })
      );

      // Grant CloudTrail permissions
      func.addToRolePolicy(
        new iam.PolicyStatement({
          actions: ['cloudtrail:LookupEvents', 'cloudtrail:StartQuery', 'cloudtrail:GetQueryResults'],
          resources: [eventDataStore.attrEventDataStoreArn],
        })
      );
    };

    // Helper function to create Python Lambda functions
    const createPythonFunction = (
      id: string,
      handler: string,
      additionalEnvVars: Record<string, string> = {}
    ): lambdaPython.PythonFunction => {
      const func = new lambdaPython.PythonFunction(this, id, {
        runtime: lambda.Runtime.PYTHON_3_14,
        handler: handler,
        entry: path.join(__dirname, '../../lambda/backend'),
        bundling: {
          assetExcludes: ['.venv', '.mypy_cache', '__pycache__']
        },
        environment: {
          ELEVATOR_ADMIN_GROUP: props.elevatorAdminGroup,
          ELEVATOR_AUDITOR_GROUP: props.elevatorAuditorGroup,
          REQUESTS_TABLE: requestsTable.tableName,
          APPROVERS_TABLE: approversTable.tableName,
          SETTINGS_TABLE: settingsTable.tableName,
          ELIGIBILITY_TABLE: eligibilityTable.tableName,
          POLICY_TABLE_NAME: eligibilityTable.tableName, // Using eligibility table for policies
          INTEGRATIONS_TABLE: integrationsTable.tableName,
          SNS_TOPIC_ARN: notificationTopic.topicArn,
          ELEVATOR_LOGIN_URL: primaryLoginUrl,
          IDC_REGION: props.idcRegion || this.region,
          EVENT_DATA_STORE_ARN: eventDataStore.attrEventDataStoreArn,
          ACCOUNT_ID: this.account,
          REVOKE_RULE_NAME: `elevator-revoke-rule-${envName}`,
          ...(additionalEnvVars || {}),
        },
        timeout: cdk.Duration.seconds(60),
        memorySize: 512,
      });

      grantCommonPermissions(func);
      return func;
    };

    // Revocation Lambda function - EventBridge scheduled revocation events
    // Created first so its ARN can be referenced by backend function
    const revocationFunction = createPythonFunction('RevocationFunction', 'revocation_handler', {
      AUTH_ELEVATOR_USERPOOLID: this.userPool.userPoolId, // Add UserPool ID for functions that need it
    });

    // Backend Lambda function - HTTP API Gateway REST API
    const backendFunction = createPythonFunction('BackendFunction', 'backend_handler', {
      AUTH_ELEVATOR_USERPOOLID: this.userPool.userPoolId, // Add UserPool ID for functions that need it
      REVOCATION_FUNCTION_ARN: revocationFunction.functionArn, // Reference revocation function ARN
    });

    // Grant Cognito permissions for backend
    backendFunction.addToRolePolicy(
      new iam.PolicyStatement({
        actions: ['cognito-idp:ListUsers'],
        resources: [this.userPool.userPoolArn],
      })
    );

    // Pre-Token Lambda function - Separate Lambda to avoid circular dependency with UserPool
    // This Lambda has minimal dependencies and doesn't need UserPool ID
    const preTokenFunction = new lambdaPython.PythonFunction(this, 'PreTokenFunction', {
      runtime: lambda.Runtime.PYTHON_3_14,
      index: 'index.py',
      handler: 'handler',
      entry: path.join(__dirname, '../../lambda/pretoken'),
      bundling: {
        assetExcludes: ['.venv', '.mypy_cache', '__pycache__']
      },
      environment: {
        SETTINGS_TABLE: settingsTable.tableName,
        ELEVATOR_ADMIN_GROUP: props.elevatorAdminGroup,
        ELEVATOR_AUDITOR_GROUP: props.elevatorAuditorGroup,
        IDC_REGION: props.idcRegion || this.region,
      },
      timeout: cdk.Duration.seconds(30),
      memorySize: 256,
    });

    // Grant permissions to pre-token function
    settingsTable.grantReadData(preTokenFunction);

    // Grant SSO Admin and Identity Store permissions for pre-token function
    preTokenFunction.addToRolePolicy(
      new iam.PolicyStatement({
        actions: [
          'sso:ListInstances',
        ],
        resources: ['*'],
      })
    );

    preTokenFunction.addToRolePolicy(
      new iam.PolicyStatement({
        actions: [
          'identitystore:GetUserId',
          'identitystore:GetGroupId',
          'identitystore:ListGroupMembershipsForMember',
        ],
        resources: ['*'],
      })
    );

    // Note: Step Functions permissions removed - all workflow logic is now handled directly in Lambda

    // Note: DynamoDB streams removed - all request processing is now synchronous via API Gateway
    // Requests are processed immediately when created/updated through API Gateway

    // Add Cognito trigger for pre-token generation
    // This creates a cycle
    this.userPool.addTrigger(cognito.UserPoolOperation.PRE_TOKEN_GENERATION, preTokenFunction);

    // =============================================================================
    // API Gateway Routes
    // =============================================================================
    // All routes are handled by proxy integration - backend Lambda handles routing

    // Add proxy route to API Gateway - all requests go to backend Lambda
    this.api.addRoutes({
      path: '/{proxy+}',
      methods: [
        apigatewayv2.HttpMethod.GET,
        apigatewayv2.HttpMethod.POST,
        apigatewayv2.HttpMethod.PUT,
        apigatewayv2.HttpMethod.DELETE,
        apigatewayv2.HttpMethod.PATCH,
      ],
      integration: new apigatewayv2Integrations.HttpLambdaIntegration('BackendProxyIntegration', backendFunction),
      authorizer,
    });

    // =============================================================================
    // EventBridge Scheduler for Scheduled Tasks
    // =============================================================================

    // Create IAM role for EventBridge Scheduler to invoke the revocation Lambda
    const schedulerRole = new iam.Role(this, 'SchedulerRole', {
      assumedBy: new iam.ServicePrincipal('scheduler.amazonaws.com'),
      description: 'Role for EventBridge Scheduler to invoke revocation Lambda',
    });
    revocationFunction.grantInvoke(schedulerRole);

    // Grant EventBridge Scheduler permissions to backend function
    backendFunction.addToRolePolicy(
      new iam.PolicyStatement({
        actions: ['scheduler:CreateSchedule', 'scheduler:DeleteSchedule', 'scheduler:GetSchedule'],
        resources: ['*'],
      })
    );

    // Grant PassRole permission for the scheduler role
    backendFunction.addToRolePolicy(
      new iam.PolicyStatement({
        actions: ['iam:PassRole'],
        resources: [schedulerRole.roleArn],
        conditions: {
          StringEquals: {
            'iam:PassedToService': 'scheduler.amazonaws.com',
          },
        },
      })
    );

    // Add scheduler role ARN to backend function environment
    backendFunction.addEnvironment('SCHEDULER_ROLE_ARN', schedulerRole.roleArn);

    // Grant EventBridge Scheduler permissions to revocation function (for cleanup)
    revocationFunction.addToRolePolicy(
      new iam.PolicyStatement({
        actions: ['scheduler:DeleteSchedule', 'scheduler:GetSchedule'],
        resources: ['*'],
      })
    );

    // =============================================================================
    // Outputs
    // =============================================================================

    new cdk.CfnOutput(this, 'UserPoolId', {
      value: this.userPool.userPoolId,
      description: 'Cognito User Pool ID',
    });

    new cdk.CfnOutput(this, 'UserPoolClientId', {
      value: this.userPoolClient.userPoolClientId,
      description: 'Cognito User Pool Client ID',
    });

    new cdk.CfnOutput(this, 'OAuthDomain', {
      value: userPoolDomain.domainName,
      description: 'Cognito OAuth Domain',
    });

    new cdk.CfnOutput(this, 'ApiUrl', {
      value: this.api.apiEndpoint,
      description: 'API Gateway HTTP API URL',
    });

    new cdk.CfnOutput(this, 'ApiId', {
      value: this.api.apiId,
      description: 'API Gateway HTTP API ID',
    });

    new cdk.CfnOutput(this, 'Region', {
      value: this.region,
      description: 'AWS Region',
    });

    new cdk.CfnOutput(this, 'WebsiteBucketName', {
      value: websiteBucket.bucketName,
      description: 'S3 Bucket for website hosting',
    });

    new cdk.CfnOutput(this, 'DistributionDomainName', {
      value: distribution.distributionDomainName,
      description: 'CloudFront Distribution Domain Name',
    });

    new cdk.CfnOutput(this, 'DistributionId', {
      value: distribution.distributionId,
      description: 'CloudFront Distribution ID',
    });

    new cdk.CfnOutput(this, 'WebsiteURL', {
      value: siteUrl,
      description: 'Website URL',
    });
  }
}
