/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /requests/{request_id} */
        get: operations["get_request_requests__request_id__get"];
        /** PUT /requests/{request_id} */
        put: operations["update_request_requests__request_id__put"];
        post?: never;
        /** DELETE /requests/{request_id} */
        delete: operations["delete_request_requests__request_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvers/{approver_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /approvers/{approver_id} */
        get: operations["get_approver_approvers__approver_id__get"];
        /** PUT /approvers/{approver_id} */
        put: operations["update_approver_approvers__approver_id__put"];
        post?: never;
        /** DELETE /approvers/{approver_id} */
        delete: operations["delete_approver_approvers__approver_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/{integration_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** PUT /integrations/{integration_name} */
        put: operations["update_integration_integrations__integration_name__put"];
        post?: never;
        /** DELETE /integrations/{integration_name} */
        delete: operations["delete_integration_integrations__integration_name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eligibility/{policy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /eligibility/{policy_id} */
        get: operations["get_eligibility_policy_eligibility__policy_id__get"];
        /** PUT /eligibility/{policy_id} */
        put: operations["update_eligibility_policy_eligibility__policy_id__put"];
        post?: never;
        /** DELETE /eligibility/{policy_id} */
        delete: operations["delete_eligibility_policy_eligibility__policy_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ou/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /ou/{account_id} */
        get: operations["get_ou_by_account_id_ou__account_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /requests/{request_id}/logs */
        post: operations["start_request_logs_requests__request_id__logs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}/grant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /requests/{request_id}/grant */
        post: operations["grant_request_requests__request_id__grant_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /requests/{request_id}/revoke */
        post: operations["revoke_request_requests__request_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /requests */
        get: operations["list_requests_requests_get"];
        put?: never;
        /** POST /requests */
        post: operations["create_request_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /settings */
        get: operations["get_settings_settings_get"];
        /** PUT /settings */
        put: operations["update_settings_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/approvers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /approvers */
        get: operations["list_approvers_approvers_get"];
        put?: never;
        /** POST /approvers */
        post: operations["create_approver_approvers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /integrations */
        get: operations["list_integrations_integrations_get"];
        put?: never;
        /** POST /integrations */
        post: operations["create_integration_integrations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/on-call": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /on-call */
        get: operations["get_on_call_users_on_call_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eligibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /eligibility */
        get: operations["list_eligibility_eligibility_get"];
        put?: never;
        /** POST /eligibility */
        post: operations["create_eligibility_policy_eligibility_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /accounts */
        get: operations["list_accounts_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ous": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /ous */
        get: operations["list_ous_ous_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /permissions */
        get: operations["list_permissions_permissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mgmt-permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /mgmt-permissions */
        get: operations["get_mgmt_permissions_mgmt_permissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/idc-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /idc-groups */
        get: operations["list_idc_groups_idc_groups_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /users */
        get: operations["list_users_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /logs */
        get: operations["list_logs_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /user-policy */
        get: operations["get_user_policy_user_policy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /groups/members */
        get: operations["list_groups_groups_members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /policy */
        post: operations["publish_policy_policy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountInfo
         * @description AWS Account information
         */
        AccountInfo: {
            /** Name */
            name: string;
            /** Id */
            id: string;
        };
        /**
         * ApproverResponse
         * @description Response model for approver
         */
        ApproverResponse: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Name */
            name: string;
            /** Groupids */
            groupIds: string[];
            /** Groupnames */
            groupNames?: string[] | null;
        };
        /**
         * ApproversListResponse
         * @description Response model for listing approvers
         */
        ApproversListResponse: {
            /** Items */
            items: components["schemas"]["ApproverResponse"][];
        };
        /**
         * CloudTrailLogEntry
         * @description CloudTrail log entry
         */
        CloudTrailLogEntry: {
            [key: string]: unknown;
        };
        /**
         * CloudTrailQueryResponse
         * @description CloudTrail query response
         */
        CloudTrailQueryResponse: {
            /** Queryid */
            queryId: string;
            /** Status */
            status: string;
        };
        /**
         * CreateApproverInput
         * @description Input model for creating an approver mapping
         */
        CreateApproverInput: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "Account" | "OU";
            /** Name */
            name: string;
            /** Groupids */
            groupIds: string[];
            /** Groupnames */
            groupNames?: string[] | null;
        };
        /**
         * CreateEligibilityInput
         * @description Input model for creating eligibility
         */
        CreateEligibilityInput: {
            /** Id */
            id: string;
            /** Accounts */
            accounts: {
                [key: string]: string;
            }[];
            /** Ous */
            ous: {
                [key: string]: string;
            }[];
            /** Permissions */
            permissions: {
                [key: string]: string;
            }[];
            /** Approvalrequired */
            approvalRequired: boolean;
            /** Duration */
            duration: string;
            /** Autoapprovaloncall */
            autoApprovalOnCall: boolean;
            /** Allowselfapproval */
            allowSelfApproval: boolean;
        } & {
            [key: string]: unknown;
        };
        /**
         * CreateIntegrationInput
         * @description Input model for creating an integration
         */
        CreateIntegrationInput: {
            /**
             * Name
             * @constant
             */
            name: "betterstack";
            /** Params */
            params: {
                [key: string]: string;
            };
        };
        /**
         * CreateRequestInput
         * @description Input model for creating a new request
         */
        CreateRequestInput: {
            /** Accountid */
            accountId: string;
            /** Accountname */
            accountName: string;
            /** Roleid */
            roleId: string;
            /** Role */
            role: string;
            /** Justification */
            justification: string;
            /** Ticketno */
            ticketNo: string;
            /** Duration */
            duration: string;
            /** Starttime */
            startTime?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * DynamoDBScanResponse
         * @description DynamoDB scan response
         */
        DynamoDBScanResponse: {
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /** Lastkey */
            lastKey?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * EligibilityListResponse
         * @description Response model for listing eligibility policies
         */
        EligibilityListResponse: {
            /** Items */
            items: components["schemas"]["EligibilityResponse"][];
        };
        /**
         * EligibilityResponse
         * @description Response model for eligibility/policy
         */
        EligibilityResponse: {
            /** Id */
            id: string;
            /** Type */
            type?: string | null;
            /** Name */
            name?: string | null;
            /** Accounts */
            accounts: {
                [key: string]: string;
            }[];
            /** Ous */
            ous: {
                [key: string]: string;
            }[];
            /** Permissions */
            permissions: {
                [key: string]: string;
            }[];
            /** Approvalrequired */
            approvalRequired: boolean;
            /** Duration */
            duration: string;
            /** Autoapprovaloncall */
            autoApprovalOnCall: boolean;
            /** Allowselfapproval */
            allowSelfApproval: boolean;
        };
        /**
         * EntitlementPolicy
         * @description Policy in entitlement response
         */
        EntitlementPolicy: {
            /** Accounts */
            accounts: {
                [key: string]: string;
            }[];
            /** Permissions */
            permissions: {
                [key: string]: string;
            }[];
            /** Approvalrequired */
            approvalRequired: boolean;
            /** Duration */
            duration: string;
            /** Autoapprovaloncall */
            autoApprovalOnCall: boolean;
            /** Allowselfapproval */
            allowSelfApproval: boolean;
        };
        /**
         * EntitlementResponse
         * @description Response model for entitlement
         */
        EntitlementResponse: {
            /** Id */
            id: string;
            /** Policy */
            policy: components["schemas"]["EntitlementPolicy"][];
            /** Username */
            username: string;
        };
        /**
         * GrantRequestResponse
         * @description Response for grant request API endpoint
         */
        GrantRequestResponse: {
            /** Status */
            status: string;
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Request */
            request: {
                [key: string]: unknown;
            };
        };
        /**
         * GroupInfo
         * @description Identity Center Group information
         */
        GroupInfo: {
            /** Groupid */
            GroupId: string;
            /** Displayname */
            DisplayName: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IntegrationListResponse
         * @description Response model for listing integrations
         */
        IntegrationListResponse: {
            /** Items */
            items: components["schemas"]["IntegrationResponse"][];
        };
        /**
         * IntegrationResponse
         * @description Response model for an integration
         */
        IntegrationResponse: {
            /** Name */
            name: string;
            /** Params */
            params: {
                [key: string]: string;
            };
        };
        /**
         * ManagementPermissionsResponse
         * @description Management account permissions response
         */
        ManagementPermissionsResponse: {
            /** Permissions */
            permissions: string[];
        };
        /**
         * OUInfo
         * @description Organizational Unit information
         */
        OUInfo: {
            /** Id */
            Id: string;
            /** Name */
            Name?: string | null;
        };
        /**
         * OnCallResponse
         * @description Response model for on-call users
         */
        OnCallResponse: {
            /** Users */
            users: components["schemas"]["OnCallUser"][];
            /** Provider */
            provider: string;
        };
        /**
         * OnCallUser
         * @description User currently on-call
         */
        OnCallUser: {
            /** Email */
            email: string;
            /** Name */
            name?: string | null;
        };
        /**
         * PermissionSetInfo
         * @description Permission Set information
         */
        PermissionSetInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * RequestItem
         * @description DynamoDB request item model
         */
        RequestItem: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Username */
            username: string;
            /** Accountid */
            accountId: string;
            /** Accountname */
            accountName: string;
            /** Roleid */
            roleId: string;
            /** Role */
            role: string;
            /** Userid */
            userId?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "approved" | "rejected" | "scheduled" | "in_progress" | "granted" | "revoked" | "cancelled" | "expired" | "error" | "ended";
            /** Sessionstatus */
            sessionStatus?: ("not-started" | "in-progress" | "finished") | null;
            /** Time */
            time?: string | null;
            /** Duration */
            duration?: string | null;
            /** Starttime */
            startTime?: string | null;
            /** Endtime */
            endTime?: string | null;
            /** Justification */
            justification?: string | null;
            /** Ticketno */
            ticketNo?: string | null;
            /**
             * Approvalrequired
             * @default true
             */
            approvalRequired: boolean;
            /** Allowselfapproval */
            allowSelfApproval?: boolean | null;
            /** Approvers */
            approvers?: string[] | null;
            /** Approver Ids */
            approver_ids?: string[] | null;
            /** Approver */
            approver?: string | null;
            /** Approverid */
            approverId?: string | null;
            /** Revoker */
            revoker?: string | null;
            /** Revokerid */
            revokerId?: string | null;
            /** Session Duration */
            session_duration?: string | null;
            /** Error */
            error?: string | null;
            /** Queryid */
            queryId?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * RevokeRequestResponse
         * @description Response for revoke request API endpoint
         */
        RevokeRequestResponse: {
            /** Status */
            status: string;
            /** Result */
            result: {
                [key: string]: unknown;
            };
            /** Request */
            request: {
                [key: string]: unknown;
            };
        };
        /**
         * SettingsItem
         * @description DynamoDB settings item model
         */
        SettingsItem: {
            /**
             * Id
             * @constant
             */
            id: "settings";
            /**
             * Approval
             * @default true
             */
            approval: boolean | null;
            /**
             * Expiry
             * @default 3
             */
            expiry: number | null;
            /**
             * Duration
             * @default 9
             */
            duration: string | null;
            /**
             * Comments
             * @default true
             */
            comments: boolean | null;
            /**
             * Sesnotificationsenabled
             * @default false
             */
            sesNotificationsEnabled: boolean | null;
            /** Sessourceemail */
            sesSourceEmail?: string | null;
            /** Sessourcearn */
            sesSourceArn?: string | null;
            /**
             * Snsnotificationsenabled
             * @default false
             */
            snsNotificationsEnabled: boolean | null;
            /**
             * Slacknotificationsenabled
             * @default false
             */
            slackNotificationsEnabled: boolean | null;
            /** Slacktoken */
            slackToken?: string | null;
            /** Slackauditnotificationschannel */
            slackAuditNotificationsChannel?: string | null;
            /** Teamadmingroup */
            teamAdminGroup?: string | null;
            /** Teamauditorgroup */
            teamAuditorGroup?: string | null;
            /**
             * Ticketno
             * @default true
             */
            ticketNo: boolean | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * SuccessResponse
         * @description Generic success response
         */
        SuccessResponse: {
            /**
             * Success
             * @default true
             */
            success: boolean;
            /** Message */
            message?: string | null;
        };
        /**
         * UpdateApproverInput
         * @description Input model for updating an approver mapping
         */
        UpdateApproverInput: {
            /** Groupids */
            groupIds: string[];
            /** Groupnames */
            groupNames?: string[] | null;
        };
        /**
         * UpdateIntegrationInput
         * @description Input model for updating an integration
         */
        UpdateIntegrationInput: {
            /** Params */
            params: {
                [key: string]: string;
            };
        };
        /**
         * UpdateRequestInput
         * @description Input model for updating a request
         */
        UpdateRequestInput: {
            /** Id */
            id: string;
            /** Status */
            status?: string | null;
            /** Approver */
            approver?: string | null;
            /** Approverid */
            approverId?: string | null;
            /** Revoker */
            revoker?: string | null;
            /** Revokerid */
            revokerId?: string | null;
            /** Email */
            email?: string | null;
            /** Approvers */
            approvers?: string[] | null;
            /** Approver Ids */
            approver_ids?: string[] | null;
            /** Session Duration */
            session_duration?: string | null;
            /** Userid */
            userId?: string | null;
            /** Approvalrequired */
            approvalRequired?: boolean | null;
            /** Allowselfapproval */
            allowSelfApproval?: boolean | null;
            /** Comment */
            comment?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * UpdateSettingsInput
         * @description Input model for updating settings
         */
        UpdateSettingsInput: {
            /** Approval */
            approval?: boolean | null;
            /** Expiry */
            expiry?: number | null;
            /** Duration */
            duration?: string | null;
            /** Comments */
            comments?: boolean | null;
            /** Sesnotificationsenabled */
            sesNotificationsEnabled?: boolean | null;
            /** Sessourceemail */
            sesSourceEmail?: string | null;
            /** Sessourcearn */
            sesSourceArn?: string | null;
            /** Snsnotificationsenabled */
            snsNotificationsEnabled?: boolean | null;
            /** Slacknotificationsenabled */
            slackNotificationsEnabled?: boolean | null;
            /** Slacktoken */
            slackToken?: string | null;
            /** Slackauditnotificationschannel */
            slackAuditNotificationsChannel?: string | null;
            /** Teamadmingroup */
            teamAdminGroup?: string | null;
            /** Teamauditorgroup */
            teamAuditorGroup?: string | null;
            /** Ticketno */
            ticketNo?: boolean | null;
        };
        /**
         * UserInfo
         * @description Identity Center User information
         */
        UserInfo: {
            /** Userid */
            UserId: string;
            /** Username */
            UserName: string;
        };
        /**
         * UserPolicyRequest
         * @description Request model for user policy
         */
        UserPolicyRequest: {
            /** Userid */
            userId: string;
            /** Groupids */
            groupIds?: string[] | null;
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Error Type */
            type: string;
        };
        /** ResponseValidationError */
        ResponseValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_request_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_request_requests__request_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRequestInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_request_requests__request_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_approver_approvers__approver_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approver_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproverResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_approver_approvers__approver_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approver_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateApproverInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproverResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_approver_approvers__approver_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approver_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_integration_integrations__integration_name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                integration_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateIntegrationInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_integration_integrations__integration_name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                integration_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_eligibility_policy_eligibility__policy_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EligibilityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_eligibility_policy_eligibility__policy_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEligibilityInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EligibilityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_eligibility_policy_eligibility__policy_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ou_by_account_id_ou__account_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OUInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_request_logs_requests__request_id__logs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudTrailQueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grant_request_requests__request_id__grant_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantRequestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_request_requests__request_id__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeRequestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_requests_requests_get: {
        parameters: {
            query?: {
                limit?: string | null;
                lastKey?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DynamoDBScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_request_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRequestInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_settings_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingsInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_approvers_approvers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproversListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_approver_approvers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApproverInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproverResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_integrations_integrations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_integration_integrations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIntegrationInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_on_call_users_on_call_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnCallResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_eligibility_eligibility_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EligibilityListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_eligibility_policy_eligibility_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEligibilityInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EligibilityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_accounts_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ous_ous_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OUInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_permissions_permissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionSetInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mgmt_permissions_mgmt_permissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagementPermissionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_idc_groups_idc_groups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_logs_logs_get: {
        parameters: {
            query?: {
                queryId?: string | null;
                query?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudTrailQueryResponse"] | components["schemas"]["CloudTrailLogEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_policy_user_policy_get: {
        parameters: {
            query?: {
                userId?: string | null;
                groupIds?: string | null;
                username?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitlementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_groups_groups_members_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_policy_policy_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPolicyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitlementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
